pr:
- master

jobs:

- job: BuildAndTest
  pool:
    vmImage: 'win1803'

  steps:
  - task: PowerShell@2
    displayName: 'Setup Build Environment'

    inputs:

      targetType: 'inline'
      script: |
        Install-Module -Name Psake, PSDeploy, BuildHelpers -Force -Scope CurrentUser
        Install-Module -Name Pester -Force -SkipPublisherCheck -Scope CurrentUser
      errorActionPreference: 'stop'
      failOnStderr: true
      pwsh: false

  - task: PowerShell@2
    displayName: 'Run Pester Tests'

    inputs:
      targetType: 'filePath'
      filePath: ./Build/Build.ps1
      arguments: -Task Build

      errorActionPreference: 'stop'
      failOnStderr: true
      pwsh: false

  - task: PowerShell@2
    condition: startsWith(variables['Build.SourceBranch'], 'refs/heads/master')
    displayName: 'Deploy to Gallery'

    inputs:
      targetType: 'filePath'
      arguments: $(GalleryApiKey)
      filePath: ./PSGallery.ps1

      errorActionPreference: 'stop'
      failOnStderr: true
      pwsh: true